# Generated by Django 5.2.1 on 2025-06-27 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_alter_achievement_options_achievement_secret_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userachievement",
            constraint=models.UniqueConstraint(
                fields=("user", "achievement"), name="unique_user_achievement"
            ),
        ),
    ]
