# Generated by Django 6.0.5 on 2026-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('progress', '0010_usersrs_delete_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
