# Generated by Django 6.0.5 on 2026-06-11 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('progress', '0011_userachievement_is_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='secret',
            new_name='is_secret',
        ),
    ]
