# Generated by Django 6.0.5 on 2026-06-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dictionary', '0002_rename_and_fix'),
        ('progress', '0012_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrs',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='srs',
                                       to='dictionary.word'),
        ),
    ]
