# Generated by Django 6.0.5 on 2026-07-07 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_sync_model_state'),
        ('progress', '0015_rename_games_db_objects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrs',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srs', to='dictionary.word'),
        ),
        migrations.AlterUniqueTogether(
            name='usersrs',
            unique_together={('user', 'word')},
        ),
    ]
