# Generated by Django 6.0.5 on 2026-07-07 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0016_alter_usersrs_word_alter_usersrs_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersrs',
            options={'verbose_name': 'SRS объект', 'verbose_name_plural': 'SRS объекты'},
        ),
        migrations.AddField(
            model_name='usersrs',
            name='ease_factor',
            field=models.FloatField(default=2.5, verbose_name='Коэффициент лёгкости'),
        ),
        migrations.AddField(
            model_name='usersrs',
            name='repetitions',
            field=models.PositiveIntegerField(default=0, verbose_name='Успешных повторений подряд'),
        ),
        migrations.AlterField(
            model_name='usersrs',
            name='access_timer',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующее повторение'),
        ),
        migrations.AlterField(
            model_name='usersrs',
            name='interval',
            field=models.PositiveIntegerField(default=1, verbose_name='Интервал в днях'),
        ),
    ]
