# Generated by Django 6.0.5 on 2026-07-10 06:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0017_alter_usersrs_options_usersrs_ease_factor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['user', 'achievement'], 'verbose_name': 'User achievement', 'verbose_name_plural': 'User achievements'},
        ),
        migrations.AlterModelOptions(
            name='usersrs',
            options={'verbose_name': 'SRS object', 'verbose_name_plural': 'SRS objects'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_secret',
            field=models.BooleanField(default=False, verbose_name='Secret achievement'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.achievement', verbose_name='Achievement'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Award date and time'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usersrs',
            name='access_timer',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Next review'),
        ),
        migrations.AlterField(
            model_name='usersrs',
            name='ease_factor',
            field=models.FloatField(default=2.5, verbose_name='Ease factor'),
        ),
        migrations.AlterField(
            model_name='usersrs',
            name='interval',
            field=models.PositiveIntegerField(default=1, verbose_name='Interval in days'),
        ),
        migrations.AlterField(
            model_name='usersrs',
            name='repetitions',
            field=models.PositiveIntegerField(default=0, verbose_name='Successful repetitions in a row'),
        ),
    ]
