# Generated by Django 6.0.5 on 2026-07-15 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_topic_remove_category_dictionary__created_b25d24_idx_and_more'),
        ('progress', '0019_achievement_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('EN_TO_RU', 'English → Russian'), ('RU_TO_EN', 'Russian → English'), ('AUDIO_TO_EN', 'Audio → English')], max_length=20, verbose_name='Learning mode')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=12, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study session',
                'verbose_name_plural': 'Study sessions',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='UserWordModeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('EN_TO_RU', 'English → Russian'), ('RU_TO_EN', 'Russian → English'), ('AUDIO_TO_EN', 'Audio → English')], max_length=20, verbose_name='Learning mode')),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='Interval in days')),
                ('repetitions', models.PositiveIntegerField(default=0, verbose_name='Successful repetitions in a row')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='Ease factor')),
                ('next_review_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Next review')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_mode_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_progress', to='dictionary.word')),
            ],
            options={
                'verbose_name': 'Word mode progress',
                'verbose_name_plural': 'Word mode progress records',
            },
        ),
        migrations.CreateModel(
            name='StudySessionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered')], default='PENDING', max_length=12)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='progress.studysession')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cards', to='progress.userwordmodeprogress')),
            ],
            options={
                'verbose_name': 'Study session card',
                'verbose_name_plural': 'Study session cards',
                'ordering': ('position',),
            },
        ),
        migrations.DeleteModel(
            name='UserSRS',
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user', 'mode'), name='unique_active_session_per_mode'),
        ),
        migrations.AddIndex(
            model_name='userwordmodeprogress',
            index=models.Index(fields=['user', 'mode', 'completed', 'next_review_at'], name='progress_due_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='userwordmodeprogress',
            constraint=models.UniqueConstraint(fields=('user', 'word', 'mode'), name='unique_user_word_learning_mode'),
        ),
        migrations.AddConstraint(
            model_name='studysessioncard',
            constraint=models.UniqueConstraint(fields=('session', 'progress'), name='unique_progress_per_session'),
        ),
        migrations.AddConstraint(
            model_name='studysessioncard',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_position_per_session'),
        ),
    ]
