# Generated by Django 6.0.5 on 2026-07-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionary", "0005_remove_word_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SRSReviewLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("review_type", models.CharField(choices=[("SRS", "SRS review")], default="SRS", max_length=32)),
                ("user_answer", models.TextField(blank=True)),
                ("correct_answer", models.TextField()),
                ("is_correct", models.BooleanField()),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("interval_before", models.PositiveIntegerField()),
                ("interval_after", models.PositiveIntegerField()),
                ("ease_factor_before", models.FloatField()),
                ("ease_factor_after", models.FloatField()),
                ("repetitions_before", models.PositiveIntegerField(default=0)),
                ("repetitions_after", models.PositiveIntegerField(default=0)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="srs_review_logs", to=settings.AUTH_USER_MODEL)),
                ("word", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_logs", to="dictionary.word")),
            ],
            options={"verbose_name": "SRS review log", "verbose_name_plural": "SRS review logs", "ordering": ["-reviewed_at"]},
        ),
        migrations.AddIndex(model_name="srsreviewlog", index=models.Index(fields=["user", "reviewed_at"], name="statistics__user_id_ec599b_idx")),
        migrations.AddIndex(model_name="srsreviewlog", index=models.Index(fields=["user", "word", "reviewed_at"], name="statistics__user_id_0a20e3_idx")),
        migrations.AddIndex(model_name="srsreviewlog", index=models.Index(fields=["user", "is_correct", "reviewed_at"], name="statistics__user_id_554e7d_idx")),
    ]
