# Generated by Django 5.2.1 on 2025-06-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_word_srs_hours_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='srs_hours_interval',
        ),
    ]
