# Generated by Django 5.2.1 on 2025-06-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_word_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='transcription',
        ),
        migrations.AlterField(
            model_name='word',
            name='russian_name',
            field=models.CharField(max_length=100, verbose_name='Слово на русском'),
        ),
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('LEARNED', 'Изучено'), ('PROCESS', 'Изучается')], default='PROCESS', max_length=10, verbose_name='Статус'),
        ),
    ]
