# Generated by Django 6.0.5 on 2026-06-24 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_category_options"),
        ("dictionary", "0001_move_from_core"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="Word"),
                migrations.DeleteModel(name="Category"),
            ],
        )
    ]
