# Generated by Django 5.2.1 on 2025-06-07 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_srs_access_timer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="srs",
            name="access_timer",
        ),
    ]
