# Generated by Django 6.0.5 on 2026-06-24 19:19

import django.db.models.deletion
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_category_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Category",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                        ("name", models.CharField(max_length=100, verbose_name="Название")),
                        ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Категория",
                        "verbose_name_plural": "Категории",
                        "ordering": ["id"],
                        "db_table": "core_category",
                        "indexes": [
                            models.Index(fields=["created_at", "updated_at"], name="core_catego_created_b420d1_idx")
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="Word",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                        ("english_name", models.CharField(max_length=100, verbose_name="Слово на английском")),
                        ("russian_name", models.CharField(max_length=100, verbose_name="Слово на русском")),
                        ("slug", models.SlugField(blank=True, null=True, unique=True, verbose_name="Slug")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("status", models.CharField(
                            choices=[("LEARNED", "Изучено"), ("PROCESS", "Изучается")],
                            default="PROCESS",
                            max_length=20,
                            verbose_name="Статус",
                        )),
                        ("category", models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="dictionary.category",
                            verbose_name="Категория",
                        )),
                        ("user", models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="words",
                            to=settings.AUTH_USER_MODEL,
                            verbose_name="Пользователь",
                        )),
                    ],
                    options={
                        "verbose_name": "Слово",
                        "verbose_name_plural": "Слова",
                        "ordering": ["-status", "english_name"],
                        "db_table": "core_word",
                    },
                    bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
                ),
            ],
        )
    ]
