# Generated by Django 6.0.5 on 2026-07-06 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rename_and_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-status', 'english_name'], 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='dictionary__created_b25d24_idx',
            old_name='core_catego_created_b420d1_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english_name',
            field=models.CharField(max_length=100, verbose_name='English word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='word',
            name='russian_name',
            field=models.CharField(max_length=100, verbose_name='Russian word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('LEARNED', 'Learned'), ('PROCESS', 'In progress')], default='PROCESS', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_word_created_8034e6_idx" RENAME TO "dictionary__created_8e3c12_idx"',
                    reverse_sql='ALTER INDEX IF EXISTS "dictionary__created_8e3c12_idx" RENAME TO "core_word_created_8034e6_idx"',
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='word',
                    index=models.Index(fields=['created_at', 'updated_at'], name='dictionary__created_8e3c12_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name='word',
                    constraint=models.UniqueConstraint(fields=('user', 'english_name'), name='unique_user_english_word'),
                ),
            ],
        ),
    ]
