# Generated by Django 6.0.5 on 2026-07-07 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_sync_model_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_user_english_word',
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('user', 'english_name', 'russian_name'), name='unique_user_word_translation'),
        ),
    ]
