# Generated by Django 6.0.5 on 2026-07-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_remove_word_unique_user_english_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='slug',
        ),
    ]
