# Generated by Django 6.0.5 on 2026-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_remove_word_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_system', models.BooleanField(default=True, verbose_name='System topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='dictionary__created_b25d24_idx',
        ),
        migrations.RemoveField(
            model_name='word',
            name='category',
        ),
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, verbose_name='Language level'),
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJECTIVE', 'Adjective'), ('ADVERB', 'Adverb'), ('PRONOUN', 'Pronoun'), ('PREPOSITION', 'Preposition'), ('CONJUNCTION', 'Conjunction'), ('DETERMINER', 'Determiner'), ('INTERJECTION', 'Interjection'), ('NUMERAL', 'Numeral'), ('PHRASE', 'Phrase'), ('OTHER', 'Other')], max_length=20, verbose_name='Part of speech'),
        ),
        migrations.AddField(
            model_name='word',
            name='register',
            field=models.CharField(blank=True, choices=[('NEUTRAL', 'Neutral'), ('FORMAL', 'Formal'), ('INFORMAL', 'Informal'), ('SLANG', 'Slang'), ('TECHNICAL', 'Technical'), ('LITERARY', 'Literary'), ('OLD_FASHIONED', 'Old-fashioned')], max_length=20, verbose_name='Usage register'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['created_at', 'updated_at'], name='dictionary__created_8ec176_idx'),
        ),
        migrations.AddField(
            model_name='word',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='words', to='dictionary.topic', verbose_name='Topics'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
