# Generated by Django 6.0.5 on 2026-07-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_create_moderators_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Attempts')),
                ('last_error', models.TextField(blank=True, verbose_name='Last error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notification', to='support.supportrequest', verbose_name='Support request')),
            ],
            options={
                'verbose_name': 'Telegram notification',
                'verbose_name_plural': 'Telegram notifications',
            },
        ),
    ]
