# Generated by Django 5.2.1 on 2025-06-07 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_srs_access_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='srs',
            name='access_timer',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время доступа к повторению'),
        ),
    ]
