# Generated by Django 5.2.1 on 2025-06-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_srs_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srs',
            name='repetitions',
        ),
    ]
